= Project Cleanup Operator

== Overview

This repository contains the code to build a Project Cleanup Operator for Red Hat OpenShift Container Platform. It will not run on Kubernetes because it uses the `Project` object which is unique to Red Hat OpenShift Container Platform.

The Operator will look for a cluster scoped custom resource *ProjectCleanup* that contains the configuration for the operator. The configuration contains the default cleanup period for projects and project name prefixes to ignore. Only one such CR can exist in the cluster and it should be named *default*.

If the Project creationTimestamp is older than the the current timestamp minus the maximum age in days specified the project is deleted - unless the project name starts with a prefix to be ignored.

== Building the Operator

The operator was created initially using this SDK command:

[source,sh]
----
operator-sdk new --type ansible --kind ProjectCleanup --api-version gpte.opentlc.com/v1alpha1 --generate-playbook  --skip-git-init --cluster-scoped project-cleanup-operator
----

There is a script `build.sh` which will build the container image and push it to a container registry. If you want to build this operator yourself you will need to adjust the repository and image name - because you would not have access to the `quay.io/gpte-devops-automation` repository.

If you decide to build your own also make sure to update both `image` settings in deploy/operator.yaml with the updated container image location.

== Installation

=== Common Installation Steps

Insatlling this operator requires cluster administrator permissions. Either use `system:admin` or a user id that has been granted the `cluster-admin` role. 

Perform the following tasks as *cluster-admin*:

. Deploy the Custom Resource Definition:
+
[source,sh]
----
oc create -f https://raw.githubusercontent.com/redhat-gpte-devopsautomation/project-cleanup-operator/master/deploy/crds/gpte_v1alpha1_projectcleanup_crd.yaml
----

. Create the Cluster Role for the Operator:
+
[source,sh]
----
oc create -f https://raw.githubusercontent.com/redhat-gpte-devopsautomation/project-cleanup-operator/master/deploy/role.yaml
----

. Create a project for the operator to run in:
+
[source,sh]
----
oc new-project gpte-project-cleanup-operator --display-name="GPTE User Quota Operator"
----

. Deploy the *project-cleanup-operator* service account (change the project name if you deployed into a different project):
+
[source,sh]
----
oc create -f https://raw.githubusercontent.com/redhat-gpte-devopsautomation/project-cleanup-operator/master/deploy/service_account.yaml -n gpte-project-cleanup-operator
----

. Grant the *project-cleanup-operator* role to the *project-cleanup-operator* service account (change the project name if you deployed into a different project):
+
[source,sh]
----
oc adm policy add-cluster-role-to-user project-cleanup-operator -z project-cleanup-operator -n gpte-project-cleanup-operator
----

. And finally create the User Project Cleanup Operator (change the project name if you deployed into a different project):
+
[source,sh]
----
oc create -f https://raw.githubusercontent.com/redhat-gpte-devopsautomation/project-cleanup-operator/master/deploy/operator.yaml -n gpte-project-cleanup-operator
----

. Once the Operator pod is running the Operator is ready to start reacting to the creation of *ProjectCleanup* object called *default*.

== Configuring the ProjectCleanup Operator

A ClusterReosurceQuota is assigned to all users by createing a Custom Resource based on the User Quota Custom Resource Definition. There is an example of a project-cleanup CR at https://github.com/redhat-gpte-devopsautomation/project-cleanup-operator/blob/master/deploy/crds/gpte_v1alpha1_project-cleanup_cr.yaml.

The Project Cleanup Operator understands the following settings under it's *spec* setting:

* ignore_project_prefix: An array of project prefixes. Projects containing these strings will never be deleted. Default: [ default, kube, openshift, gpte ]
* The next three variables configure the maximum age of projects. The actual expiration gets calculated as maxDaysOld*24*60 + maxHoursOld*60 + maxMinutesOld. To delete projects every hour set maxDaysOld=0, maxHoursOld=1, maxMinutesOld=0 (or maxDaysOld=0, maxHoursOld=0, maxMinutesOld=60).
** maxDaysOld: The maximum age of projects in days. Default: 7 days
** maxHoursOld: The maximum age of projects in hours. Default 0 hours
** maxMinutesOld: The maximum age of projects in minutes. Default 0 minutes

[NOTE]
Currently the name of this object *has* to be `default`.

.Example
[source,texinfo]
----
apiVersion: gpte.opentlc.com/v1alpha1
kind: ProjectCleanup
metadata:
  name: default
spec:
  # Ignore projects/namespaces starting with these strings
  ignore_project_prefix:
  - default
  - kube-
  - openshift-
  - gpte-
  # Maximum age of projects in days
  # Projects that are older than this setting will be deleted
  # Granularity is minutes
  # This will be calculated as:
  #   maxDaysOld*24*60 + maxHoursOld*60 + maxMinutesOld
  maxDaysOld: 7
  maxHoursOld: 0
  maxMinutesOld: 0
----

. Write the definition to a file (e.g. project-cleanup.yaml) and then create the project-cleanup instance:
+
[source,sh]
----
oc create -f ./project-cleanup.yaml
----

== Deleting a ClusterResourceQuotas

When the ProjectCleanup object is removed from the OpenShift the operator will continue to run but will no longer delete projects.

[source,sh]
----
oc delete ProjectCleanup default
----

== Uninstalling the Project Cleanup Operator

In case you wish to uninstall the Project Cleanupd Operator make sure that the ProjectC-cleanup object `default` has been deleted. Then simply delete the project the operator is running in.

[source,sh]
----
oc delete project project-cleanup-operator
----

Then as *cluster-admin* delete the ClusterRole and Custom Resource:

[source,sh]
----
oc delete clusterrole project-cleanup-operator
oc delete crd projectcleanup.gpte.opentlc.com
----

