apiVersion: gpte.opentlc.com/v1alpha1
kind: ProjectCleanup
metadata:
  name: example-projectcleanup
spec:
  # Ignore projects/namespaces starting with these strings
  ignore_project_prefix:
    - openshift
    - gpte
  # Maximum age of projects in days
  # Projects that are older than this setting will be deleted
  cleanupAge: 7
