apiVersion: gpte.opentlc.com/v1alpha1
kind: ProjectCleanup
metadata:
  name: default
spec:
  # Ignore projects/namespaces starting with these strings
  ignore_project_prefix:
  - default
  - kube-
  - openshift-
  - gpte-
  # Maximum age of projects in days
  # Projects that are older than this setting will be deleted
  # Granularity is minutes
  # This will be calculated as:
  #   maxDaysOld*24*50 + maxHoursOld*60 + maxMinutesOld
  maxDaysOld: 7
  maxHoursOld: 0
  maxMinutesOld: 0