---
# creationTimestamp: 2019-04-23T23:58:39Z
#                    YYYY-MM-DDTHH:MM:SSZ

- name: Print debug information
  debug:
    msg: "Found Project {{ project_name }} created {{ project_creation_timestamp }}, cutoff: {{ project_deletion_threshold }}"

- name: Set flag to notFound
  set_fact:
    project_name_valid: True

- name: Check if project name starts with an exclusion
  set_fact:
    project_name_valid: False
  when: project_name is match(project_prefix + "*")
  loop: "{{ project_ignore_prefix_list }}"
  loop_control:
    loop_var: project_prefix

- name: Print if project will be considered because it's name does not start with a ignored prefix
  debug:
    msg: "Project {{ project_name }} will be considered: {{ project_name_valid|bool }}"

# - name: Print if project would be eligible for deletion
#   debug:
#     msg: "Would delete project {{ project_name }}..."
#   when:
#   - project_name_valid|bool
#   - project_creation_timestamp < project_deletion_threshold

- name: Delete Project because it is older than allowed and doesn't start with an ignored prefix
  k8s:
    api_version: project.openshift.io/v1
    kind: Project
    name: "{{ project_name }}"
    state: absent
  when:
  - project_name_valid|bool
  - project_creation_timestamp < project_deletion_threshold
